# Generated by Django 5.0.1 on 2024-01-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dns_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team_id', models.IntegerField()),
                ('team_name', models.CharField(max_length=30)),
                ('team_email', models.EmailField(max_length=254)),
                ('intern_net', models.BooleanField()),
                ('ip', models.IntegerField()),
                ('opertation_sys', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='React',
        ),
    ]
