# Generated by Django 5.0.1 on 2024-01-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_vm_intern_net_vm_allocationstage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vm',
            old_name='team_email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='vm',
            old_name='dns_name',
            new_name='hostname',
        ),
        migrations.RenameField(
            model_name='vm',
            old_name='team_name',
            new_name='project_name',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='external_net',
        ),
        migrations.RemoveField(
            model_name='vm',
            name='team_id',
        ),
        migrations.AddField(
            model_name='vm',
            name='awarded_on',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
