# Generated by Django 5.0.1 on 2024-01-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_vm_intern_net_vm_allocationstage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm',
            name='ip',
            field=models.CharField(max_length=20),
        ),
    ]
