# Generated by Django 5.0.1 on 2024-01-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_vm_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm',
            name='ip',
            field=models.GenericIPAddressField(),
        ),
    ]
