# Generated by Django 5.0.1 on 2024-01-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_team_email_vm_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm',
            name='contact_email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vm',
            name='project_name',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
