# Generated by Django 5.0.1 on 2024-01-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_vm_contact_email_alter_vm_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='contact_name',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
    ]
