# Generated by Django 5.0.1 on 2024-01-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_vm_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm',
            name='contact_name',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
