# Generated by Django 5.0.1 on 2024-01-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_vm_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm',
            name='operating_sys',
            field=models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux')], max_length=20),
        ),
    ]
