# Generated by Django 5.0.1 on 2024-01-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_vm_operating_sys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vm',
            name='allocationStage',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('preparation', 'Preparation'), ('in_use', 'In_use'), ('blocked', 'Blocked')], default='unassigned', max_length=20),
        ),
    ]
