= Projektplan: {project-name}
Paul Kiok <paul.kiok@stud.htw-dresden.de>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
Wir als das Team I05-Virtuelle Maschinen verwenden zur Strukturierung unseres Projektes eine abgewandelte Version des Open Unified Process. 

Der Projektplan wird fortlaufend erweitert. Die Verantwortlichkeit, zur Pflege des Projektplans liegt beim Projektmanager. 


== Projektorganisation
//Introduce the project team, team members, and roles that they play during this project. If applicable, introduce work areas, domains, or technical work packages that are assigned to team members. Introduce neighboring projects, relationships, and communication channels. If the project is introduced somewhere else, reference that location with a link.
Die Rollen der einzelnen Mitglieder werden in der xref:responsibilities.adoc#_rollenuebersicht_[Rollenübersicht] beschrieben. Dabei werden auch Aufgaben erwähnt, welche nicht in der Klassischen Rollendefinition des Open UP genannt sind.

Es findet ein wöchentliches Meeting im 6. Unterrichtsblock der HTW Dresden statt, also immer montags von 17:00-18:30. Das Meeting erfolgt in hybrider Form, von der wir uns maximale Flexibilität für die Teilnehmer und minimale Wartezeiten nach dem 5. Unterrichtsblock erhoffen. Die Remote-Teilnehmer werden mittles BigBlueButton in das Meeting inkludiert. Neben den hybriden wöchentlichen Meetings findet die Kommunikation über WhatsApp, Discord und GitHub statt.

WhatsApp wird verwendet, um auf kurzem Wege alle Teammitglieder an kommende Meetings, wichtige Entwicklungen in Github oder Deadlines zu erinnern. 

Im Discord treffen sich Teilmengen der Gruppenmitglieder, um Dokumentationen zu bearbeiten oder Co-Coding Sessions zu realisieren. Außerdem werden Terminabstimmungen mithilfe eines Umfrage-Bots realisiert um möglichst einfach die Wünsche aller Mitglieder zu berücksichtigen.

GitHub stellt die Struktur zur Verfügung, welche wir zur Aufgabenverwaltung und -verteilung verwenden. 

== Praktiken und Bewertung
//Describe or reference which management and technical practices will be used in the project, such as iterative development, continuous integration, independent testing and list any changes or particular configuration to the project. Specify how you will track progress in each practice. As an example, for iterative development the team may decide to use iteration assessments and iteration burndown reports and collect metrics such as velocity (completed work item points/ iteration).
=== Management Praktiken
Wir verwenden das https://www2.htw-dresden.de/~anke/openup/practice.mgmt.iterative_dev.base/guidances/practices/iterative_development_CD1297B8.html[Iterative Deployment] des Open UP, um unsere Aufgaben zu strukturieren.

Dabei erstellen wir Iterationen, die jeweils *14 Tage* dauern. Um alle Iterationen inkl. Aufgaben zu verwalten, wird im GitHub ein *Projekt* angelegt. Innerhalb des Projektes wird ein auf unsere Bedürfnisse abgewandeltes Kanban Board verwendet (https://github.com/users/henrikalbrecht/projects/2[I05-Iterationplan]). Jede Iteration beinhaltet eine Reihe von Aufgaben, welche bewältigt werden müssen. Die Aufgaben werden zu Beginn der Iteration definiert, als Issues in Github eingetragen und bestmöglich nach den Wünschen und Fähigkeiten der Gruppenmitglieder verteilt. So sind auch nachträgliche Änderungen bei der Vergabe möglich, sofern erforderlich.

Die Verteilung der Aufgaben nach den Fähigkeiten und Wünschen begünstigt die zweite Management Praktik des Open UP die wir verwenden, https://www2.htw-dresden.de/~anke/openup/index.htm[Whole Team]. Begonnen haben wir damit als wir die Rollen innerhalb des Teams auf Grundlage der Wünsche jedes einzelnen verteilt haben. Weiterhin verwenden wir regelmäßige *Teamevents* um das "Wir-Gefühl" zu stärken.  Um den Wissenstand innerhalb des Teams so gleichmäßig wie möglich zu halten verwenden wir Workshops, beispielsweise für GitHub um jeden einzelnen an die Funktionalitäten heranzuführen und das Wissen zu streuen. Die Erkenntnisse der Workshops werden außerdem im https://github.com/henrikalbrecht/I05-Virtuelle-Maschinen/wiki[Wiki] zusammengetragen.

Die wöchentlichen Meetings werden genutzt, um unseren Stand in der aktuellen Iteration darzustellen und Informationen aus den Projektgeber-Meetings mit allen Teammitgliedern zu teilen. Darüber hinaus nutzen wir es als Möglichkeit, um Wissen in Form von Workshops oder Präsentationen innerhalb des gesamten Teams zu vermitteln und Erfahrungen auszutauschen.

Um allen Teammitgliedern die Möglichkeit im gleichen Maße seine Ideen und Vorschläge in das Projekt einzubringen nutzen wir unsere GitHub Issues welche in einem https://github.com/users/henrikalbrecht/projects/2/views/1[Projekt] organisiert sind. Diese Praktik spiegelt die Inhalte des https://www2.htw-dresden.de/~anke/openup/index.htm[Team Change Managements] aus dem Open UP wieder.

=== Technische Praktiken
Um die Verwendung von GitHub zu strukturieren und praxisorientiert zu arbeiten, verwenden wir den https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow[GitHub Feature Branch Workflow].

== Meilensteine und Ziele
//Define and describe the high-level objectives for the iterations and define milestones. For example, use the following table to lay out the schedule. If needed you may group the iterations into phases and use a separate table for each phase

[%header, cols="1,3a,2,1"]
|===
| Iteration
| Primary objectives +
(risks and use case scenarios)
| start and end date
| Target velocity

| I1
|
* Teamfindung und Kennenlernen
* Verteilung der Rollen
* Einigung auf gemeinsame Arbeitsweise
* Kennenlernen der Aufgabe
* Kontaktaufnahme und Treffen mit Auftraggeber
* Kontaktaufnahme und Treffen mit Coach
| 06.11.2023-19.11.2023
| 14

| I2
|
* Erarbeitung und Finalisierung der Vision
* Erstellung eines groben grafischen Prototyps zu Abbildung der Hauptfunktionalität
* Workshop für alle mit Github
| 20.11.2023-03.12.2023
| 14

| I3
|
* Erstellung des Use-Case Models
* Ausarbeitung von UC01
* Ausarbeitung von UC03
* Weiterbildung für alle mit Github
* Workshop für Developer und Tester
* Erarbeitung der Risikoliste
| 04.12.2023-17.12.2023
| 14

| I4
|
* TODO
| 18.12.2023-31.12.2023
| 14

| I5
|
* TODO
| 01.01.2024-14.01.2024
| 14

| I6
|
* TODO
| 15.01.2024-28.01.2024
| 14
|===


== Deployment
//Outline the strategy for deploying the software (and its updates) into the production environment.


== Erkenntnisse (Lessons learned)
//List lessons learned from the retrospective, with special emphasis on actions to be taken to improve, for example: the development environment, the process, or team collaboration.
